// Generated by CoffeeScript 1.12.6
(function() {
  var exports, fill;

  exports = this;

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    return "Filling the " + container + " with " + liquid + "...";
  };

  $(function() {
    console.log("DOM is ready");
    return $('#dynamic').html(fill('cup'));
  });

}).call(this);

//# sourceMappingURL=main.js.map
